import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Wrappper from "@/components/LayoutWrapper";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="csrf-token" content="{{ csrf_token() }}"></meta>
      <body className={inter.className}>
        <Wrappper>
        <Header/>
          {children}
        </Wrappper>
      </body>
    </html>
  );
}
